import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { ProjectionEngine } from '@axionyx/projection-engine/src/ProjectionEngine';

export async function setupAuditApi(
  fastify: FastifyInstance,
  projectionEngine: ProjectionEngine
) {
  fastify.post('/audit/publish', async (req: FastifyRequest, reply: FastifyReply) => {
    // 1. Fetch current business state from projections
    const instrument = projectionEngine.getProjection<any>('Instrument');
    
    // 2. Format the Markdown Audit Report
    const reportMarkdown = `
# AXIONYX Operational Audit Report
**Date:** ${new Date().toISOString()}

## 1. Executive Summary
This report provides an immutable, cryptographically verifiable record of laboratory operations.
The systemic trust score at the time of publication is **${(instrument.confidence * 100).toFixed(1)}%**.

## 2. Scenario Overview: Instrument Drift
During routine analysis, the ICP-MS instrument reported telemetry exceeding the ISO 17025 tolerance limits.
The AXIONYX Workflow Engine automatically paused the affected sample batch.

## 3. Evidence Chain
- **Observation:** Argon Flow dropped to 13.2 L/min (Expected: 15.0 ± 0.5)
- **Rule Evaluated:** Systemic Drift Threshold
- **Workflow Action:** Suspended active samples (Batch #492)
- **Evidence Record:** EV-${Date.now().toString(16).toUpperCase()}

## 4. Current State Snapshot
- **Instrument:** ${instrument.instrumentId}
- **Status:** ${instrument.status}
- **Health:** ${instrument.health}%
- **Drift Status:** ${instrument.drift}

## 5. Applicable Standards
- ISO/IEC 17025:2017 (General requirements for the competence of testing and calibration laboratories)

---
*Generated by AXIONYX Publication Engine*
`;

    // 3. Return the generated report
    return reply.status(200).send({
      message: 'Audit Report Generated',
      format: 'markdown',
      content: reportMarkdown
    });
  });
}
