# Default values for axionyx.

replicaCount: 1

image:
  repository: axionyx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: axionyx.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
