// AXIONYX PUBLIC INFRASTRUCTURE FOR KNOWLEDGE
// packages/publishing-engine/examples/demo.ts

import { PublishingEngine } from '../src/index';
import { GoogleClassroomConnector } from '../../connectors/src/lms/google-classroom/index';
import { PublishContext } from '../../connectors/src/common/index';

async function runDemo() {
  console.log("===============================================================");
  console.log(`AXIONYX PUBLISHING ENGINE DEMO`);
  console.log("===============================================================\n");

  const engine = new PublishingEngine();
  
  // Register the Universal Connectors
  const gcConnector = new GoogleClassroomConnector();
  engine.registerConnector(gcConnector);

  // Define the Context (Normally generated by the Compiler -> Assessment Engine)
  const context: PublishContext = {
    investigationId: 'INV-001',
    audience: 'Academy',
    format: 'Markdown',
    content: '# Investigation: Nitrogen Deficiency...',
    metadata: {
      domain: 'Agriculture'
    }
  };

  try {
    // Route through the Publishing Engine
    const url = await engine.publishTo('google-classroom', context);
    console.log(`\n>>> PUBLISH SUCCESSFUL`);
    console.log(`>>> DESTINATION URL: ${url}`);
  } catch (error) {
    console.error(`Publishing Failed:`, error);
  }
}

runDemo();
