import React, { useState, useEffect } from 'react';
import { Book, Microscope, HardHat, FileCheck, Droplets, Link as LinkIcon } from 'lucide-react';

const domains = [
  { id: 'coal', name: 'Coal Intelligence', icon: <Microscope className="w-6 h-6 text-emerald-400" /> },
  { id: 'vehicles', name: 'Vehicle Intelligence', icon: <HardHat className="w-6 h-6 text-blue-400" /> },
  { id: 'engineering', name: 'Engineering Intelligence', icon: <Book className="w-6 h-6 text-purple-400" /> },
  { id: 'equipment', name: 'Industrial Equipment', icon: <FileCheck className="w-6 h-6 text-yellow-400" /> },
  { id: 'water', name: 'Environmental Intelligence', icon: <Droplets className="w-6 h-6 text-cyan-400" /> },
];

export default function Observatory() {
  const [activeDomain, setActiveDomain] = useState('water');
  const [pubs, setPubs] = useState<string>('Loading publications from Knowledge Publication Engine...');

  useEffect(() => {
    // In a real app, this would fetch from the `/dist/publications` backend via an API.
    // For this demo, we simulate loading the generated markdown.
    setTimeout(() => {
      setPubs(\`# Why Calibration Creates Trust in IoT Sensors\\n\\nA raw pH reading of 7.35 is meaningless without proof of accuracy.\\n\\n---\\n\\n### Verifiable Evidence\\n- [EVIDENCE CITATION: CALIBRATION-RECORD-001] -> Reality Artifact Cryptographically Traced\\n- [EVIDENCE CITATION: IOT-SENSOR-DESIGN-001] -> Reality Artifact Cryptographically Traced\`);
    }, 500);
  }, []);

  return (
    <div className="flex space-x-8">
      <div className="w-1/4 space-y-4">
        <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Reality Domain Explorer</h2>
        {domains.map(d => (
          <button 
            key={d.id} 
            onClick={() => setActiveDomain(d.id)}
            className={\`w-full text-left flex items-center space-x-3 px-4 py-3 rounded-lg border transition-colors \${activeDomain === d.id ? 'bg-gray-800 border-blue-500 shadow-md' : 'border-gray-800 hover:bg-gray-800 hover:border-gray-700'}\`}
          >
            {d.icon}
            <span className="font-semibold">{d.name}</span>
          </button>
        ))}
      </div>
      
      <div className="w-3/4 bg-gray-800 p-8 rounded-2xl border border-gray-700 shadow-xl min-h-[600px]">
        <div className="flex justify-between items-center mb-8 border-b border-gray-700 pb-4">
          <h2 className="text-3xl font-bold text-gray-100 flex items-center space-x-3">
            {domains.find(d => d.id === activeDomain)?.icon}
            <span>{domains.find(d => d.id === activeDomain)?.name}</span>
          </h2>
          <span className="px-3 py-1 bg-blue-900/50 text-blue-300 rounded-full text-sm font-mono border border-blue-800 flex items-center">
             <LinkIcon className="w-3 h-3 mr-2"/> Cryptographically Verified
          </span>
        </div>
        
        <div className="prose prose-invert max-w-none">
          <p className="text-gray-400 italic mb-8">This public article was automatically generated by the AXIONYX Knowledge Publication Engine directly from underlying industrial evidence.</p>
          <div className="bg-gray-900 p-6 rounded-lg font-mono text-sm border border-gray-700 whitespace-pre-wrap text-gray-300">
            {activeDomain === 'water' ? pubs : 'Select Environmental Intelligence to view the generated publication.'}
          </div>
        </div>
      </div>
    </div>
  );
}
